/**
 * AUTO-GENERATED by scripts/gen-src-map.js — do not edit by hand.
 * Run "node scripts/gen-src-map.js" to regenerate after adding music files.
 *
 * Maps track ID -> exact URL-encoded /music/ path, resolved from real filenames.
 * Player uses this for instant zero-latency audio resolution.
 */
export const TRACK_SRC_MAP: Record<string, string> = {
  "1": "/music/Coldplay%20-%20Paradise%20(Official%20Video).mp3", // Coldplay - Paradise (Official Video).mp3
  "2": "/music/Coldplay%20-%20In%20My%20Place%20(Official%204K%20Video).mp3", // Coldplay - In My Place (Official 4K Video).mp3
  "5": "/music/Coldplay%20-%20Fix%20You%20(Official%20Video).mp3", // Coldplay - Fix You (Official Video).mp3
  "10": "/music/Coldplay%20-%20Magic%20(Official%20Video)%20%5BOfficial%5D.mp3", // Coldplay - Magic (Official Video) [Official].mp3
  "16": "/music/Coldplay%20-%20Violet%20Hill%20(Official%20Video).mp3", // Coldplay - Violet Hill (Official Video).mp3
  "17": "/music/Coldplay%20-%20Everglow%20%5BSingle%20Version%5D%20-%20(Official%20Video).mp3", // Coldplay - Everglow [Single Version] - (Official Video).mp3
  "18": "/music/Coldplay%20-%20Miracles%20(Official%20Lyric%20Video).mp3", // Coldplay - Miracles (Official Lyric Video).mp3
  "19": "/music/Coldplay%20-%20Up%26Up%20(Official%20Video).mp3", // Coldplay - Up&Up (Official Video).mp3
  "20": "/music/Talk%20Is%20Cheap.mp3", // Talk Is Cheap.mp3
  "21": "/music/Feel%20-%20Avi%20Snow%2C%20MVCA%2C%20Zeeba%20(AI%20Music%20Video).mp3", // Feel - Avi Snow, MVCA, Zeeba (AI Music Video).mp3
  "28": "/music/The%20XX%20Intro%20-%20ELEZO%20remix%20(%20Official%20video%20).mp3", // The XX Intro - ELEZO remix ( Official video ).mp3
  "29": "/music/Supermode%20-%20Tell%20Me%20Why%20(James%20Carter%20Remix).mp3", // Supermode - Tell Me Why (James Carter Remix).mp3
  "30": "/music/Dezko%20%26%20CERES%20-%20U%26ME%20(Visualizer).mp3", // Dezko & CERES - U&ME (Visualizer).mp3
  "31": "/music/Marius%20Bear%20-%20Horizon%20(Official%20Video).mp3", // Marius Bear - Horizon (Official Video).mp3
  "32": "/music/In%20The%20Air%20Tonight-%20%20Jon%20Howard%20(Official%20Audio).mp3", // In The Air Tonight-  Jon Howard (Official Audio).mp3
  "33": "/music/Livin%E2%80%99%20on%20Borrowed%20Time.mp3", // Livin’ on Borrowed Time.mp3
  "53": "/music/Jamie%20N%20Commons%20-%20Lead%20Me%20Home%20(The%20Walking%20Dead).mp3", // Jamie N Commons - Lead Me Home (The Walking Dead).mp3
  "34": "/music/Croixx%20-%20Higher%20(Official%20Lyric%20Video).mp3", // Croixx - Higher (Official Lyric Video).mp3
  "35": "/music/Martin%20Wave%20feat.%20ASHBY%20-%20Watch%20Me%20Die%20(From%20The%20Terminal%20List)%20%5BFULL%20SONG%5D.mp3", // Martin Wave feat. ASHBY - Watch Me Die (From The Terminal List) [FULL SONG].mp3
  "36": "/music/Alex%20Warren%20-%20Ordinary%20(Official%20Video).mp3", // Alex Warren - Ordinary (Official Video).mp3
  "47": "/music/Hans%20Zimmer%20-%20A%20Dark%20Knight%20%EF%BD%9C%20EPIC%20VERSION.mp3", // Hans Zimmer - A Dark Knight ｜ EPIC VERSION.mp3
  "54": "/music/Ima%20Robot%20-%20Greenback%20Boogie%20-%20(official%20video).mp3", // Ima Robot - Greenback Boogie - (official video).mp3
  "37": "/music/Old%20Man%20Canyon%20-%20Phantoms%20%26%20Friends%20%5BOfficial%20Video%5D.mp3", // Old Man Canyon - Phantoms & Friends [Official Video].mp3
  "38": "/music/Passenger%20%EF%BD%9C%20Let%20Her%20Go%20(Official%20Video).mp3", // Passenger ｜ Let Her Go (Official Video).mp3
  "39": "/music/Here%20We%20Go.mp3", // Here We Go.mp3
  "40": "/music/Bobby%20Bazini%20-%20Blood's%20Thicker%20Than%20Water%20(Audio).mp3", // Bobby Bazini - Blood's Thicker Than Water (Audio).mp3
  "41": "/music/Mirror%20Fury%20-%20The%20One%20I%20Love.mp3", // Mirror Fury - The One I Love.mp3
  "42": "/music/Louis%20Armstrong%20-%20What%20A%20Wonderful%20World%20(Official%20Video).mp3", // Louis Armstrong - What A Wonderful World (Official Video).mp3
  "43": "/music/NOVRA%20%E2%80%93%20Before%20The%20Fall%20%EF%BD%9C%20Emotional%20Deep%20House.mp3", // NOVRA – Before The Fall ｜ Emotional Deep House.mp3
  "44": "/music/The%20Veils%20-%20Grey%20Lynn%20Park.mp3", // The Veils - Grey Lynn Park.mp3
  "45": "/music/Michael%20Jackson%20-%20Man%20In%20The%20Mirror%20(Official%20Video).mp3", // Michael Jackson - Man In The Mirror (Official Video).mp3
  "46": "/music/Dan%20Wilson%20-%20Breathless.mp3", // Dan Wilson - Breathless.mp3
  "48": "/music/Lord%20Huron%20-%20The%20Night%20We%20Met%20(Official%20Audio).mp3", // Lord Huron - The Night We Met (Official Audio).mp3
  "49": "/music/Charlie%20Cunningham%20-%20Permanent%20Way%20(Live%20Session).mp3", // Charlie Cunningham - Permanent Way (Live Session).mp3
  "50": "/music/Neil%20Diamond%20-%20Sweet%20Caroline%20(Audio).mp3", // Neil Diamond - Sweet Caroline (Audio).mp3
  "51": "/music/The%20Three%20Tenors%20in%20Concert%201994%EF%BC%9A%20%EF%BC%82Nessun%20Dorma%EF%BC%82%20from%20Turandot%20(encore).mp3", // The Three Tenors in Concert 1994： ＂Nessun Dorma＂ from Turandot (encore).mp3
  "52": "/music/C%C3%A9line%20Dion%20-%20Ashes%20(from%20%EF%BC%82Deadpool%202%EF%BC%82%20Motion%20Picture%20Soundtrack).mp3", // Céline Dion - Ashes (from ＂Deadpool 2＂ Motion Picture Soundtrack).mp3
  "58": "/music/Survivor%20-%20Eye%20Of%20The%20Tiger%20(Official%20HD%20Video).mp3", // Survivor - Eye Of The Tiger (Official HD Video).mp3
  "55": "/music/O%20Meri%20Laila%20-%20Lyrical%20%EF%BD%9C%20Laila%20Majnu%20%EF%BD%9C%20Jyotica%20Tangri%20%EF%BD%9C%20Avinash%20Tiwary%20%26%20Tripti%20Dimri.mp3", // O Meri Laila - Lyrical ｜ Laila Majnu ｜ Jyotica Tangri ｜ Avinash Tiwary & Tripti Dimri.mp3
  "56": "/music/Keane%20-%20Somewhere%20Only%20We%20Know%20(Official%20Music%20Video).mp3", // Keane - Somewhere Only We Know (Official Music Video).mp3
  "57": "/music/Wrabel%20-%20Into%20The%20Wild%20(Audio).mp3", // Wrabel - Into The Wild (Audio).mp3
  "59": "/music/Turin%20Brakes%20-%20Save%20You%20(Official%20Video).mp3", // Turin Brakes - Save You (Official Video).mp3
  "61": "/music/Elderbrook%20-%20Inner%20Light%20with%20Bob%20Moses%20(Official%20Music%20Video).mp3", // Elderbrook - Inner Light with Bob Moses (Official Music Video).mp3
  "62": "/music/Alphaville%20-%20Big%20In%20Japan%20(Official%20Music%20Video).mp3", // Alphaville - Big In Japan (Official Music Video).mp3
  "63": "/music/Charlotte%20OC%20-%20Colour%20My%20Heart%20(Official%20Video).mp3", // Charlotte OC - Colour My Heart (Official Video).mp3
  "64": "/music/Dean%20Lewis%20-%20Waves%20(Official%20Video).mp3", // Dean Lewis - Waves (Official Video).mp3
  "65": "/music/Logic%20%26%20Rag'n'Bone%20Man%20-%20Broken%20People%20(from%20Bright%EF%BC%9A%20The%20Album)%20%5BOfficial%20Lyric%20Video%5D.mp3", // Logic & Rag'n'Bone Man - Broken People (from Bright： The Album) [Official Lyric Video].mp3
  "66": "/music/Faouzia%20%26%20John%20Legend%20-%20Minefields%20(Official%20Music%20Video).mp3", // Faouzia & John Legend - Minefields (Official Music Video).mp3
  "67": "/music/Robbie%20Williams%20-%20Man%20For%20All%20Seasons%20(Johnny%20English).mp3", // Robbie Williams - Man For All Seasons (Johnny English).mp3
  "68": "/music/Zac%20Brown%20%26%20Sir%20Rosevelt%20-%20It%20Goes%20On%20(Official%20Lyric%20Video).mp3", // Zac Brown & Sir Rosevelt - It Goes On (Official Lyric Video).mp3
  "69": "/music/Break%20The%20Silence%20%E2%A7%B8%E2%A7%B8%20The%20Dig%20%E2%A7%B8%E2%A7%B8%20Midnight%20Flowers%20(2012).mp3", // Break The Silence ⧸⧸ The Dig ⧸⧸ Midnight Flowers (2012).mp3
  "70": "/music/Desi%20Valentine%20-%20Fate%20Don't%20Know%20You.mp3", // Desi Valentine - Fate Don't Know You.mp3
  "71": "/music/Mark%20Ambor%20-%20Belong%20Together%20(Official%20Lyric%20Video).mp3", // Mark Ambor - Belong Together (Official Lyric Video).mp3
  "72": "/music/Stealth%20-%20Judgement%20Day.mp3", // Stealth - Judgement Day.mp3
  "73": "/music/Johnny%20Clegg%20-%20King%20Of%20Time.mp3", // Johnny Clegg - King Of Time.mp3
  "74": "/music/Angus%20Stone%20-%20Broken%20Brights%20Official%20Video.mp3", // Angus Stone - Broken Brights Official Video.mp3
  "75": "/music/Cadbury%20Gorilla%20-%20In%20The%20Air%20Tonight%20(Extended%20Mix).mp3", // Cadbury Gorilla - In The Air Tonight (Extended Mix).mp3
  "76": "/music/Michael%20Kiwanuka%20-%20Love%20%26%20Hate%20(Live%20Session).mp3", // Michael Kiwanuka - Love & Hate (Live Session).mp3
  "77": "/music/A.R.%20Rahman%20-%20Tere%20Bina%20%EF%BD%9C%20Lyrical%20Song%20%EF%BD%9C%20Aishwarya%20Rai%20%EF%BD%9C%20Abhishek%20Bachchan%20%EF%BD%9C%20Guru%20%EF%BD%9C%20Gulzar.mp3", // A.R. Rahman - Tere Bina ｜ Lyrical Song ｜ Aishwarya Rai ｜ Abhishek Bachchan ｜ Guru ｜ Gulzar.mp3
  "78": "/music/Star%20Wars%EF%BC%9A%20Duel%20of%20The%20Fates%20%EF%BD%9C%20EPIC%20VERSION%20(Remastered%20V2).mp3", // Star Wars： Duel of The Fates ｜ EPIC VERSION (Remastered V2).mp3
  "79": "/music/TINA%20TURNER%20%E2%98%85%20We%20Don't%20Need%20Another%20Hero%20(Thunderdome)%E3%80%90music%20video%E3%80%91.mp3", // TINA TURNER ★ We Don't Need Another Hero (Thunderdome)【music video】.mp3
  "80": "/music/Johnny%20Clegg-Great%20Heart.mp3", // Johnny Clegg-Great Heart.mp3
  "81": "/music/Scrubs%20Theme%20Song%20Superman%20Lazlo%20Bane%20Official%20Video%20Remastered%20HD.mp3", // Scrubs Theme Song Superman Lazlo Bane Official Video Remastered HD.mp3
  "82": "/music/Jos%C3%A9%20Gonz%C3%A1lez%20-%20Stay%20Alive.mp3", // José González - Stay Alive.mp3
  "83": "/music/Rocky%20Balboa%20-%20Theme%20Song%20(HD).mp3", // Rocky Balboa - Theme Song (HD).mp3
  "84": "/music/Bon%20Jovi%20-%20Young%20Guns%20II%20Blaze%20of%20Glory.mp3", // Bon Jovi - Young Guns II Blaze of Glory.mp3
  "85": "/music/Deep%20Blue%20Something%20-%20Breakfast%20At%20Tiffany's%20(Official%20Music%20Video).mp3", // Deep Blue Something - Breakfast At Tiffany's (Official Music Video).mp3
  "86": "/music/Ruth%20B.%20-%20Dandelions%20(Lyrics).mp3", // Ruth B. - Dandelions (Lyrics).mp3
  "87": "/music/Casino%20Royale%20-%20Chris%20Cornell%20-%20You%20Know%20My%20Name.mp3", // Casino Royale - Chris Cornell - You Know My Name.mp3
  "88": "/music/The%20Proclaimers%20-%20I'm%20Gonna%20Be%20(500%20Miles)%20(Official%20Music%20Video).mp3", // The Proclaimers - I'm Gonna Be (500 Miles) (Official Music Video).mp3
  "89": "/music/Lean%20on%20Me.mp3", // Lean on Me.mp3
  "90": "/music/Bon%20Jovi%20-%20It's%20My%20Life%20(Official%20Music%20Video).mp3", // Bon Jovi - It's My Life (Official Music Video).mp3
  "91": "/music/The%20Weeknd%20-%20Can't%20Feel%20My%20Face%20(Official%20Video).mp3", // The Weeknd - Can't Feel My Face (Official Video).mp3
  "92": "/music/Succession%20(Main%20Title%20Theme)%20-%20Nicholas%20Britell%20%EF%BD%9C%20Succession%20(HBO%20Original%20Series%20Soundtrack).mp3", // Succession (Main Title Theme) - Nicholas Britell ｜ Succession (HBO Original Series Soundtrack).mp3
  "93": "/music/Godzilla%20Soundtrack%20%EF%BD%9C%20Godzilla!%20-%20Alexandre%20Desplat%20%EF%BD%9C%20WaterTower%20Music.mp3", // Godzilla Soundtrack ｜ Godzilla! - Alexandre Desplat ｜ WaterTower Music.mp3
  "94": "/music/OneRepublic%20-%20Let's%20Hurt%20Tonight.mp3", // OneRepublic - Let's Hurt Tonight.mp3
  "95": "/music/The%20XX%20Intro%20-%20ELEZO%20remix%20(%20Official%20video%20).mp3", // The XX Intro - ELEZO remix ( Official video ).mp3
  "96": "/music/Hanni%20El%20Khatib%20-%20Nobody%20Move.mp3", // Hanni El Khatib - Nobody Move.mp3
  "97": "/music/Manike%20(Full%20Video)%EF%BC%9A%20Thank%20God%20%EF%BD%9C%20Nora%2CSidharth%EF%BD%9C%20Tanishk%2CYohani%2CJubin%2CSurya%20R%20%EF%BD%9CRashmi%20Virag%EF%BD%9CBhushan%20K.mp3", // Manike (Full Video)： Thank God ｜ Nora,Sidharth｜ Tanishk,Yohani,Jubin,Surya R ｜Rashmi Virag｜Bhushan K.mp3
  "98": "/music/Sheppard%20-%20Geronimo%20(Official%20Music%20Video).mp3", // Sheppard - Geronimo (Official Music Video).mp3
  "99": "/music/Ini%20Kamoze%20-%20Here%20Comes%20The%20Hotstepper%20(Remix)%20(Official%20Video).mp3", // Ini Kamoze - Here Comes The Hotstepper (Remix) (Official Video).mp3
  "100": "/music/Martin%20Garrix%20feat.%20Bonn%20-%20High%20On%20Life%20(Official%20Video).mp3", // Martin Garrix feat. Bonn - High On Life (Official Video).mp3
  "101": "/music/George%20Ezra%20-%20Budapest%20(Official%20Video).mp3", // George Ezra - Budapest (Official Video).mp3
  "102": "/music/The%20Verve%20-%20Bitter%20Sweet%20Symphony.mp3", // The Verve - Bitter Sweet Symphony.mp3
  "103": "/music/4%20Non%20Blondes%20-%20What's%20Up%20(Official%20Music%20Video).mp3", // 4 Non Blondes - What's Up (Official Music Video).mp3
  "104": "/music/Madonna%20-%20Like%20A%20Prayer%20(Choir%20Version)%20%5BVinyl%20Visualizer%5D.mp3", // Madonna - Like A Prayer (Choir Version) [Vinyl Visualizer].mp3
  "105": "/music/Dobie%20Gray%20-%20Drift%20Away%20(Original%20Official%20Video).mp3", // Dobie Gray - Drift Away (Original Official Video).mp3
  "106": "/music/THE%20CROSSING%20-%20Friends%20of%20Johnny%20Clegg.mp3", // THE CROSSING - Friends of Johnny Clegg.mp3
  "107": "/music/Elton%20John%2C%20Dua%20Lipa%20-%20Cold%20Heart%20(PNAU%20Remix)%20(Official%20Video).mp3", // Elton John, Dua Lipa - Cold Heart (PNAU Remix) (Official Video).mp3
  "108": "/music/Jacob%20Banks%20-%20Unknown%20(To%20You)%20Official%20Music%20Video.mp3", // Jacob Banks - Unknown (To You) Official Music Video.mp3
  "109": "/music/Lewis%20Capaldi%20-%20Before%20You%20Go%20(Official%20Video).mp3", // Lewis Capaldi - Before You Go (Official Video).mp3
  "110": "/music/KALEO%20-%20Way%20Down%20We%20Go%20(Official%20Music%20Video).mp3", // KALEO - Way Down We Go (Official Music Video).mp3
  "111": "/music/Rag'n'Bone%20Man%20-%20Human%20(Official%20Video).mp3", // Rag'n'Bone Man - Human (Official Video).mp3
  "112": "/music/Sam%20Smith%20-%20Stay%20With%20Me%20(Official%20Music%20Video).mp3", // Sam Smith - Stay With Me (Official Music Video).mp3
  "113": "/music/George%20Michael%2C%20Elton%20John%20-%20Don't%20Let%20The%20Sun%20Go%20Down%20On%20Me%20(Live).mp3", // George Michael, Elton John - Don't Let The Sun Go Down On Me (Live).mp3
  "114": "/music/The%20Angry%20River%20-%20The%20Hat%20ft.%20father%20John%20Misty%20(with%20lyrics).mp3", // The Angry River - The Hat ft. father John Misty (with lyrics).mp3
  "115": "/music/Lera%20Lynn%20-%20Lately.mp3", // Lera Lynn - Lately.mp3
  "116": "/music/Bill%20Withers%20-%20Lovely%20Day%20(Official%20Audio).mp3", // Bill Withers - Lovely Day (Official Audio).mp3
  "117": "/music/The%20Dark%20Knight%20Rises%20Official%20Soundtrack%20%EF%BD%9C%20Why%20Do%20We%20Fall%EF%BC%9F%20%E2%80%93%20Hans%20Zimmer%20%EF%BD%9C%20WaterTower.mp3", // The Dark Knight Rises Official Soundtrack ｜ Why Do We Fall？ – Hans Zimmer ｜ WaterTower.mp3
  "118": "/music/James%20Bay%20-%20Hold%20Back%20The%20River.mp3", // James Bay - Hold Back The River.mp3
  "119": "/music/Scorpions%20-%20Wind%20Of%20Change%20(Official%20Music%20Video).mp3", // Scorpions - Wind Of Change (Official Music Video).mp3
  "120": "/music/Aerosmith%20-%20I%20Don't%20Want%20to%20Miss%20a%20Thing%20(Official%20HD%20Video).mp3", // Aerosmith - I Don't Want to Miss a Thing (Official HD Video).mp3
  "121": "/music/John%20Newman%20-%20Love%20Me%20Again.mp3", // John Newman - Love Me Again.mp3
  "123": "/music/Eagle-Eye%20Cherry%20-%20Save%20Tonight.mp3", // Eagle-Eye Cherry - Save Tonight.mp3
  "124": "/music/Hold%20On%20Hope.mp3", // Hold On Hope.mp3
  "125": "/music/OneRepublic%20-%20Need%20Your%20Love%20(Official%20Video).mp3", // OneRepublic - Need Your Love (Official Video).mp3
  "126": "/music/ROYA%20-%20Cruise%20(Extended%20Version)%20-%20LIVE%20SESSION.mp3", // ROYA - Cruise (Extended Version) - LIVE SESSION.mp3
  "127": "/music/Astrality%20%26%20James%20French%20-%20Can%E2%80%99t%20Go%20Back.mp3", // Astrality & James French - Can’t Go Back.mp3
  "128": "/music/Never%20Did.mp3", // Never Did.mp3
  "129": "/music/One%20Last%20Waltz%20%E2%80%93%20DannyHO%20%EF%BD%9C%20Minecraft-Style%20EDM%20Visual%20%EF%BD%9C%20Afterglow%20(Track%2007).mp3", // One Last Waltz – DannyHO ｜ Minecraft-Style EDM Visual ｜ Afterglow (Track 07).mp3
  "130": "/music/Imagine%20Dragons%20-%20Shots%20(Broiler%20Remix)%20ft.%20Broiler.mp3", // Imagine Dragons - Shots (Broiler Remix) ft. Broiler.mp3
  "131": "/music/all%20things%20break%20-%20magnetic%20magnetic.mp3", // all things break - magnetic magnetic.mp3
  "132": "/music/Against%20the%20Tide%20%E2%80%93%20DannyHO%20%EF%BD%9C%20Minecraft-Style%20EDM%20Visual%20%EF%BD%9C%20Afterglow%20(Track%2004).mp3", // Against the Tide – DannyHO ｜ Minecraft-Style EDM Visual ｜ Afterglow (Track 04).mp3
  "200": "/music/Coldplay%20-%20Trouble%20(Official%20video).mp3", // Coldplay - Trouble (Official video).mp3
  "201": "/music/John%20Legend%20-%20All%20of%20Me%20(Official%20Video).mp3", // John Legend - All of Me (Official Video).mp3
  "202": "/music/Toto%20-%20Africa%20(Official%20HD%20Video).mp3", // Toto - Africa (Official HD Video).mp3
  "203": "/music/X%20Ambassadors%20-%20Renegades%20(Lyric%20Video).mp3", // X Ambassadors - Renegades (Lyric Video).mp3
  "204": "/music/Survivor%20-%20Burning%20heart%20(Rocky%20IV)%20HQ.mp3", // Survivor - Burning heart (Rocky IV) HQ.mp3
  "205": "/music/Snow%20Patrol%20-%20Open%20Your%20Eyes%20(Official%20Video).mp3", // Snow Patrol - Open Your Eyes (Official Video).mp3
  "206": "/music/Elton%20John%20-%20I'm%20Still%20Standing.mp3", // Elton John - I'm Still Standing.mp3
  "207": "/music/Dean%20Lewis%20-%20With%20You%20(Official%20Video).mp3", // Dean Lewis - With You (Official Video).mp3
  "208": "/music/Rag'n'Bone%20Man%20-%20Skin%20(Official%20Video).mp3", // Rag'n'Bone Man - Skin (Official Video).mp3
  "209": "/music/Luude%20-%20Down%20Under%20(Feat.%20Colin%20Hay)%20(Official%20Music%20Video).mp3", // Luude - Down Under (Feat. Colin Hay) (Official Music Video).mp3
  "210": "/music/Tina%20Turner%20-%20The%20Best%20(Official%20Music%20Video)%20%5BHD%20Upgrade%5D.mp3", // Tina Turner - The Best (Official Music Video) [HD Upgrade].mp3
  "211": "/music/Imagine%20-%20John%20Lennon%20%26%20The%20Plastic%20Ono%20Band%20(w%20The%20Flux%20Fiddlers)%20(Ultimate%20Mix%202018)%20-%204K%20REMASTER.mp3", // Imagine - John Lennon & The Plastic Ono Band (w The Flux Fiddlers) (Ultimate Mix 2018) - 4K REMASTER.mp3
  "212": "/music/Machine%20Gun%20Kelly%2C%20X%20Ambassadors%20%26%20Bebe%20Rexha%20-%20Home%20(from%20Bright%EF%BC%9A%20The%20Album)%20%5BOfficial%20Video%5D.mp3", // Machine Gun Kelly, X Ambassadors & Bebe Rexha - Home (from Bright： The Album) [Official Video].mp3
  "213": "/music/Tears%20For%20Fears%20-%20Everybody%20Wants%20To%20Rule%20The%20World%20(Official%20Music%20Video).mp3", // Tears For Fears - Everybody Wants To Rule The World (Official Music Video).mp3
  "214": "/music/The%20Cranberries%20-%20Zombie%20(Official%20Music%20Video).mp3", // The Cranberries - Zombie (Official Music Video).mp3
  "215": "/music/Yazoo%20-%20Only%20You%20%E2%80%A2%20TopPop.mp3", // Yazoo - Only You • TopPop.mp3
  "216": "/music/Ben%20E.%20King%20-%20Stand%20By%20Me%20(Audio).mp3", // Ben E. King - Stand By Me (Audio).mp3
  "217": "/music/Hold%20On%2C%20I'm%20Coming.mp3", // Hold On, I'm Coming.mp3
  "218": "/music/Stuck%20On%20You.mp3", // Stuck On You.mp3
  "219": "/music/Bill%20Withers%20-%20Ain't%20No%20Sunshine%20(Official%20Audio).mp3", // Bill Withers - Ain't No Sunshine (Official Audio).mp3
  "220": "/music/NOTSOBAD%20x%20MA%EF%BC%9ARK%20-%20Let%20It%20Go.mp3", // NOTSOBAD x MA：RK - Let It Go.mp3
  "221": "/music/I%20Play%20Rocky%20Trailer%20Music%20%EF%BD%9C%20EPIC%20VERSION.mp3", // I Play Rocky Trailer Music ｜ EPIC VERSION.mp3
  "222": "/music/Steelfeather%20-%20With%20The%20Devil%20I'm%20Going%20Down.mp3", // Steelfeather - With The Devil I'm Going Down.mp3
  "223": "/music/Coldplay%20-%20Hymn%20For%20The%20Weekend%20(Official%20Video).mp3", // Coldplay - Hymn For The Weekend (Official Video).mp3
  "224": "/music/Michael%20Jackson%20-%20Leave%20Me%20Alone%20(Official%20Video).mp3", // Michael Jackson - Leave Me Alone (Official Video).mp3
  "225": "/music/Alesso%20%26%20John%20Newman%20%E2%80%93%20Call%20Your%20Name%20(Official%20Lyric%20Video).mp3", // Alesso & John Newman – Call Your Name (Official Lyric Video).mp3
  "226": "/music/John%20Newman%20-%20Come%20And%20Get%20It.mp3", // John Newman - Come And Get It.mp3
  "227": "/music/Until%20The%20End%20Of%20Time%20(Julian%20Bunetta%20Remix).mp3", // Until The End Of Time (Julian Bunetta Remix).mp3
  "228": "/music/Michael%20Jackson%20-%20Is%20It%20Scary%20(Audio).mp3", // Michael Jackson - Is It Scary (Audio).mp3
  "229": "/music/The%20Devils%20Share.mp3", // The Devils Share.mp3
  "230": "/music/Michael%20Jackson%20-%20Chicago%20(Official%20Audio).mp3", // Michael Jackson - Chicago (Official Audio).mp3
  "231": "/music/Lost%20Highway%20(Official%20Video).mp3", // Lost Highway (Official Video).mp3
  "232": "/music/Lil%20Tecca%20-%20Love%20Me%20(Official%20Music%20Video).mp3", // Lil Tecca - Love Me (Official Music Video).mp3
  "233": "/music/Quarles%20%26%20Limehouse.mp3", // Quarles & Limehouse.mp3
  "234": "/music/MAISON%20ROYALE%20-%20Let%20Your%20Body%20Fly%20(visual).mp3", // MAISON ROYALE - Let Your Body Fly (visual).mp3
  "235": "/music/05%20%E2%80%A2%20%20Trent%20Dabbs%20-%20Follow%20Suit%20%26%20Paper%20Trails.mp3", // 05 •  Trent Dabbs - Follow Suit & Paper Trails.mp3
  "236": "/music/The%20Blue%20Stones%20-%20Shakin'%20Off%20The%20Rust%20%5BOfficial%20Lyric%20Video%5D.mp3", // The Blue Stones - Shakin' Off The Rust [Official Lyric Video].mp3
  "237": "/music/The%20Blue%20Stones%20-%20One%20By%20One%20(Official%20Audio).mp3", // The Blue Stones - One By One (Official Audio).mp3
  "238": "/music/John%20Mayer%20-%20Waiting%20On%20The%20World%20To%20Change.mp3", // John Mayer - Waiting On The World To Change.mp3
  "239": "/music/Michael%20Jackson%20-%20Human%20Nature%20(Official%20Video).mp3", // Michael Jackson - Human Nature (Official Video).mp3
  "240": "/music/Michael%20Jackson%20-%20Billie%20Jean%20(Official%20Video).mp3", // Michael Jackson - Billie Jean (Official Video).mp3
  "241": "/music/Michael%20Jackson%20-%20Bad%20(Shortened%20Version).mp3", // Michael Jackson - Bad (Shortened Version).mp3
  "242": "/music/Passenger%20%EF%BD%9C%20Home%20(Official%20Album%20Audio).mp3", // Passenger ｜ Home (Official Album Audio).mp3
  "243": "/music/Keane%20-%20The%20Starting%20Line%20(Acoustic).mp3", // Keane - The Starting Line (Acoustic).mp3
  "244": "/music/Noah%20Kahan%20-%20Doors%20(Official%20Lyric%20Video).mp3", // Noah Kahan - Doors (Official Lyric Video).mp3
  "245": "/music/James%20Blunt%20-%20The%20Greatest%20(Official%20Music%20Video).mp3", // James Blunt - The Greatest (Official Music Video).mp3
  "246": "/music/ODESZA%20-%20A%20Moment%20Apart%20-%20Official%20Audio.mp3", // ODESZA - A Moment Apart - Official Audio.mp3
  "247": "/music/Have%20It%20All.mp3", // Have It All.mp3
  "248": "/music/Moby%20-%20Extreme%20Ways%20(Official%20Video).mp3", // Moby - Extreme Ways (Official Video).mp3
  "249": "/music/Marshmello%20ft.%20Bastille%20-%20Happier%20(Official%20Music%20Video).mp3", // Marshmello ft. Bastille - Happier (Official Music Video).mp3
  "250": "/music/Bette%20Midler%20-%20Wind%20Beneath%20My%20Wings%20(Official%20Music%20Video).mp3", // Bette Midler - Wind Beneath My Wings (Official Music Video).mp3
  "251": "/music/Elmo%20-%20Shine%20(Lyric%20Video).mp3", // Elmo - Shine (Lyric Video).mp3
  "252": "/music/Adele%20-%20Hello%20(Official%20Music%20Video).mp3", // Adele - Hello (Official Music Video).mp3
  "253": "/music/Justin%20Timberlake%20-%20Say%20Something%20(Official%20Video)%20ft.%20Chris%20Stapleton.mp3", // Justin Timberlake - Say Something (Official Video) ft. Chris Stapleton.mp3
  "254": "/music/Hugh%20Grant%20%26%20Haley%20Bennett%20-%20Way%20Back%20Into%20Love%20(Lyrics)%201080pHD.mp3", // Hugh Grant & Haley Bennett - Way Back Into Love (Lyrics) 1080pHD.mp3
  "255": "/music/My%20Blood.mp3", // My Blood.mp3
  "256": "/music/Kal%20Ho%20Naa%20Ho%20(Title%20Track)%20-%20Full%20Video%20%EF%BD%9C%20Shah%20Rukh%20Khan%2C%20Saif%20Ali%20Khan%2C%20Preity%20Zinta%20%EF%BD%9C%20Sonu%20Nigam.mp3", // Kal Ho Naa Ho (Title Track) - Full Video ｜ Shah Rukh Khan, Saif Ali Khan, Preity Zinta ｜ Sonu Nigam.mp3
  "257": "/music/Adele%20-%20Skyfall%20(Official%20Lyric%20Video).mp3", // Adele - Skyfall (Official Lyric Video).mp3
  "258": "/music/Imagine%20Dragons%20-%20Demons%20(Official%20Music%20Video).mp3", // Imagine Dragons - Demons (Official Music Video).mp3
  "259": "/music/Billy%20Joel%20-%20We%20Didn't%20Start%20The%20Fire%20(Official%20HD%20Video).mp3", // Billy Joel - We Didn't Start The Fire (Official HD Video).mp3
  "260": "/music/Calvin%20Harris%2C%20Rihanna%20-%20This%20Is%20What%20You%20Came%20For%20(Official%20Video).mp3", // Calvin Harris, Rihanna - This Is What You Came For (Official Video).mp3
  "261": "/music/Aloe%20Blacc%20-%20Ticking%20Bomb%20(Official%20Lyric%20Video).mp3", // Aloe Blacc - Ticking Bomb (Official Lyric Video).mp3
  "262": "/music/ill%20peach%20-%20HOLD%20ON.mp3", // ill peach - HOLD ON.mp3
  "263": "/music/Jake%20Houlsby%20-%20Howl.mp3", // Jake Houlsby - Howl.mp3
  "264": "/music/Panama%20-%20Always%20%5BOfficial%20Music%20Video%5D.mp3", // Panama - Always [Official Music Video].mp3
  "265": "/music/ODESZA%20-%20Across%20The%20Room%20(feat.%20Leon%20Bridges)%20-%20Official%20Video.mp3", // ODESZA - Across The Room (feat. Leon Bridges) - Official Video.mp3
  "266": "/music/Shawn%20Colvin%20-%20Sunny%20Came%20Home.mp3", // Shawn Colvin - Sunny Came Home.mp3
  "267": "/music/Sting%20-%20Fields%20Of%20Gold.mp3", // Sting - Fields Of Gold.mp3
  "268": "/music/In%20Color%20-%20Headlights%20(Extended).mp3", // In Color - Headlights (Extended).mp3
  "269": "/music/Bennett%20Coast%20-%20Now%20I%20Know%20You.mp3", // Bennett Coast - Now I Know You.mp3
  "270": "/music/Good%20Neighbours%20-%20Home%20(Lyric%20Video).mp3", // Good Neighbours - Home (Lyric Video).mp3
  "271": "/music/Violet%20City.mp3", // Violet City.mp3
  "272": "/music/Cikho%20-%20Fell%20Again%20(Music%20Video).mp3", // Cikho - Fell Again (Music Video).mp3
  "273": "/music/Low%20Gravity.mp3", // Low Gravity.mp3
  "274": "/music/Dustin%20Tebbutt%20-%20Love%20Is%20Blind%20(Official%20Video).mp3", // Dustin Tebbutt - Love Is Blind (Official Video).mp3
  "275": "/music/Rose%20Tint.mp3", // Rose Tint.mp3
  "276": "/music/Michael%20Marcagi%20-%20Move%20On%20(Official%20Audio).mp3", // Michael Marcagi - Move On (Official Audio).mp3
  "277": "/music/Sonaba%20x%20Henry%20Chris%20-%20Sun%20is%20Dark.mp3", // Sonaba x Henry Chris - Sun is Dark.mp3
  "278": "/music/Emmit%20Fenn%20-%20The%20Chase%20(Reb%C5%ABke%20Remix).mp3", // Emmit Fenn - The Chase (Rebūke Remix).mp3
  "279": "/music/Noah%20Kahan%20-%20Porch%20Light%20(Official%20Lyric%20Video).mp3", // Noah Kahan - Porch Light (Official Lyric Video).mp3
  "280": "/music/I%E2%80%99m%20Coming%20Home%20(Fire%20Country%EF%BC%9A%20Season%202).mp3", // I’m Coming Home (Fire Country： Season 2).mp3
  "281": "/music/League%20of%20Legends%EF%BC%9A%20Arcane%20-%20Enemy%20%EF%BD%9C%20EPIC%20ORCHESTRAL%20VERSION%20(Imagine%20Dragons%20Cover).mp3", // League of Legends： Arcane - Enemy ｜ EPIC ORCHESTRAL VERSION (Imagine Dragons Cover).mp3
  "282": "/music/Misplaced%20-%20Riley%20Pearce%20(Official%20Music%20Video).mp3", // Misplaced - Riley Pearce (Official Music Video).mp3
  "283": "/music/The%20Howlers%20%20-%20%20How%20Long%20(Live%20at%20Metropolis%20Studios).mp3", // The Howlers  -  How Long (Live at Metropolis Studios).mp3
  "284": "/music/Bobby%20Bazini%20-%20Under%20The%20Weight%20(Audio).mp3", // Bobby Bazini - Under The Weight (Audio).mp3
  "285": "/music/Built%20By%20Titan%20%2B%20Skybourne%EF%BC%9A%20Times%20Are%20Changing%20(from%20the%20Freevee%20Original%20Series%20Bosch%EF%BC%9A%20Legacy).mp3", // Built By Titan + Skybourne： Times Are Changing (from the Freevee Original Series Bosch： Legacy).mp3
  "286": "/music/Gangstagrass%20-%20Long%20Hard%20Times%20To%20Come.mp3", // Gangstagrass - Long Hard Times To Come.mp3
  "287": "/music/Give%20me%20your%20love%20-%20Sigala%20ft.%20Nile%20Rodgers%20%26%20John%20Newman%20(lyric%20video).mp3", // Give me your love - Sigala ft. Nile Rodgers & John Newman (lyric video).mp3
  "288": "/music/The%20Crossing%20(Osiyeza).mp3", // The Crossing (Osiyeza).mp3
};
