/**
 * AUTO-GENERATED by scripts/gen-src-map.js — do not edit by hand.
 * Run "node scripts/gen-src-map.js" to regenerate after adding music files.
 *
 * Maps track ID -> exact URL-encoded /music/ path, resolved from real filenames.
 * Player uses this for instant zero-latency audio resolution.
 */
export const TRACK_SRC_MAP: Record<string, string> = {
  "1": "/music/Coldplay%20-%20Paradise%20(Official%20Video).mp3", // Coldplay - Paradise (Official Video).mp3
  "2": "/music/Coldplay%20-%20In%20My%20Place%20(Official%204K%20Video).mp3", // Coldplay - In My Place (Official 4K Video).mp3
  "5": "/music/Coldplay%20-%20Fix%20You%20(Official%20Video).mp3", // Coldplay - Fix You (Official Video).mp3
  "10": "/music/Coldplay%20-%20Magic%20(Official%20Video).mp3", // Coldplay - Magic (Official Video).mp3
  "16": "/music/Coldplay%20-%20Violet%20Hill%20(Official%20Video).mp3", // Coldplay - Violet Hill (Official Video).mp3
  "17": "/music/Coldplay%20-%20Everglow%20%5BSingle%20Version%5D%20-%20(Official%20Video).mp3", // Coldplay - Everglow [Single Version] - (Official Video).mp3
  "18": "/music/Coldplay%20-%20Miracles%20(Official%20Lyric%20Video).mp3", // Coldplay - Miracles (Official Lyric Video).mp3
  "19": "/music/Coldplay%20-%20Up%26Up%20(Official%20Video).mp3", // Coldplay - Up&Up (Official Video).mp3
  "28": "/music/The%20XX%20Intro%20-%20ELEZO%20remix%20(%20Official%20video%20).mp3", // The XX Intro - ELEZO remix ( Official video ).mp3
  "29": "/music/Star%20Wars%EF%BC%9A%20Duel%20of%20The%20Fates%20%EF%BD%9C%20EPIC%20VERSION%20(Remastered%20V2).mp3", // Star Wars： Duel of The Fates ｜ EPIC VERSION (Remastered V2).mp3
  "47": "/music/Hans%20Zimmer%20-%20A%20Dark%20Knight%20%EF%BD%9C%20EPIC%20VERSION.mp3", // Hans Zimmer - A Dark Knight ｜ EPIC VERSION.mp3
  "49": "/music/Jos%C3%A9%20Gonz%C3%A1lez%20-%20Stay%20Alive.mp3", // José González - Stay Alive.mp3
  "50": "/music/Casino%20Royale%20-%20Chris%20Cornell%20-%20You%20Know%20My%20Name.mp3", // Casino Royale - Chris Cornell - You Know My Name.mp3
  "53": "/music/Jamie%20N%20Commons%20-%20Lead%20Me%20Home%20(The%20Walking%20Dead).mp3", // Jamie N Commons - Lead Me Home (The Walking Dead).mp3
  "54": "/music/Ima%20Robot%20-%20Greenback%20Boogie%20-%20(official%20video).mp3", // Ima Robot - Greenback Boogie - (official video).mp3
  "57": "/music/Survivor%20-%20Burning%20heart%20(Rocky%20IV)%20HQ.mp3", // Survivor - Burning heart (Rocky IV) HQ.mp3
  "58": "/music/Survivor%20-%20Eye%20Of%20The%20Tiger%20(Official%20HD%20Video).mp3", // Survivor - Eye Of The Tiger (Official HD Video).mp3
  "201": "/music/The%20Dark%20Knight%20Rises%20Official%20Soundtrack%20%EF%BD%9C%20Why%20Do%20We%20Fall%EF%BC%9F%20%E2%80%93%20Hans%20Zimmer%20%EF%BD%9C%20WaterTower.mp3", // The Dark Knight Rises Official Soundtrack ｜ Why Do We Fall？ – Hans Zimmer ｜ WaterTower.mp3
  "204": "/music/Bon%20Jovi%20-%20Young%20Guns%20II%20Blaze%20of%20Glory.mp3", // Bon Jovi - Young Guns II Blaze of Glory.mp3
  "205": "/music/Godzilla%20Soundtrack%20%EF%BD%9C%20Godzilla!%20-%20Alexandre%20Desplat%20%EF%BD%9C%20WaterTower%20Music.mp3", // Godzilla Soundtrack ｜ Godzilla! - Alexandre Desplat ｜ WaterTower Music.mp3
  "208": "/music/Treadstone%20Assassins.mp3", // Treadstone Assassins.mp3
  "209": "/music/Rocky%20Balboa%20-%20Theme%20Song%20(HD).mp3", // Rocky Balboa - Theme Song (HD).mp3
  "212": "/music/Succession%20(Main%20Title%20Theme)%20-%20Nicholas%20Britell%20%EF%BD%9C%20Succession%20(HBO%20Original%20Series%20Soundtrack).mp3", // Succession (Main Title Theme) - Nicholas Britell ｜ Succession (HBO Original Series Soundtrack).mp3
  "400": "/music/C%C3%A9line%20Dion%20-%20Ashes%20(from%20%EF%BC%82Deadpool%202%EF%BC%82%20Motion%20Picture%20Soundtrack).mp3", // Céline Dion - Ashes (from ＂Deadpool 2＂ Motion Picture Soundtrack).mp3
  "60": "/music/Bon%20Iver%20-%20Holocene%20-%20Official%20Video.mp3", // Bon Iver - Holocene - Official Video.mp3
  "61": "/music/Skinny%20Love.mp3", // Skinny Love.mp3
  "62": "/music/Anna%20Nalick%20-%20Breathe%20(2%20AM)%20(Official%20Video).mp3", // Anna Nalick - Breathe (2 AM) (Official Video).mp3
  "64": "/music/Kacey%20Musgraves%20-%20Slow%20Burn%20(Official%20Audio).mp3", // Kacey Musgraves - Slow Burn (Official Audio).mp3
  "66": "/music/Stateless%20-%20Bloodstream%20(Official%20lyrics).mp3", // Stateless - Bloodstream (Official lyrics).mp3
  "67": "/music/Daughter%20-%20Youth.mp3", // Daughter - Youth.mp3
  "68": "/music/Medicine.mp3", // Medicine.mp3
  "230": "/music/Michael%20Kiwanuka%20-%20Love%20%26%20Hate%20(Live%20Session).mp3", // Michael Kiwanuka - Love & Hate (Live Session).mp3
  "231": "/music/Break%20The%20Silence%20%E2%A7%B8%E2%A7%B8%20The%20Dig%20%E2%A7%B8%E2%A7%B8%20Midnight%20Flowers%20(2012).mp3", // Break The Silence ⧸⧸ The Dig ⧸⧸ Midnight Flowers (2012).mp3
  "232": "/music/KALEO%20-%20Way%20Down%20We%20Go%20(Official%20Music%20Video).mp3", // KALEO - Way Down We Go (Official Music Video).mp3
  "233": "/music/James%20Bay%20-%20Hold%20Back%20The%20River.mp3", // James Bay - Hold Back The River.mp3
  "234": "/music/Lewis%20Capaldi%20-%20Before%20You%20Go%20(Official%20Video).mp3", // Lewis Capaldi - Before You Go (Official Video).mp3
  "235": "/music/Rag'n'Bone%20Man%20-%20Human%20(Official%20Video).mp3", // Rag'n'Bone Man - Human (Official Video).mp3
  "236": "/music/Keane%20-%20Somewhere%20Only%20We%20Know%20(Official%20Music%20Video).mp3", // Keane - Somewhere Only We Know (Official Music Video).mp3
  "237": "/music/Ruth%20B.%20-%20Dandelions%20(Lyrics).mp3", // Ruth B. - Dandelions (Lyrics).mp3
  "238": "/music/Jacob%20Banks%20-%20Unknown%20(To%20You)%20Official%20Music%20Video.mp3", // Jacob Banks - Unknown (To You) Official Music Video.mp3
  "239": "/music/Snow%20Patrol%20-%20Open%20Your%20Eyes%20(Official%20Video).mp3", // Snow Patrol - Open Your Eyes (Official Video).mp3
  "401": "/music/Old%20Man%20Canyon%20-%20Phantoms%20%26%20Friends%20%5BOfficial%20Video%5D.mp3", // Old Man Canyon - Phantoms & Friends [Official Video].mp3
  "402": "/music/Charlie%20Cunningham%20-%20Permanent%20Way%20(Live%20Session).mp3", // Charlie Cunningham - Permanent Way (Live Session).mp3
  "403": "/music/Wrabel%20-%20Into%20The%20Wild%20(Audio).mp3", // Wrabel - Into The Wild (Audio).mp3
  "404": "/music/Angus%20Stone%20-%20Broken%20Brights%20Official%20Video.mp3", // Angus Stone - Broken Brights Official Video.mp3
  "405": "/music/Dan%20Wilson%20-%20Breathless.mp3", // Dan Wilson - Breathless.mp3
  "406": "/music/NOVRA%20%E2%80%93%20Before%20The%20Fall%20%EF%BD%9C%20Emotional%20Deep%20House.mp3", // NOVRA – Before The Fall ｜ Emotional Deep House.mp3
  "407": "/music/Marius%20Bear%20-%20Horizon%20(Official%20Video).mp3", // Marius Bear - Horizon (Official Video).mp3
  "80": "/music/Adele%20-%20Make%20You%20Feel%20My%20Love%20(Official%20Video).mp3", // Adele - Make You Feel My Love (Official Video).mp3
  "81": "/music/Adele%20-%20Someone%20Like%20You%20(Official%20Music%20Video).mp3", // Adele - Someone Like You (Official Music Video).mp3
  "82": "/music/John%20Legend%20-%20All%20of%20Me%20(Official%20Video).mp3", // John Legend - All of Me (Official Video).mp3
  "83": "/music/Christina%20Perri%20-%20A%20Thousand%20Years%20%5BOfficial%20Music%20Video%5D.mp3", // Christina Perri - A Thousand Years [Official Music Video].mp3
  "84": "/music/Ed%20Sheeran%20-%20Perfect%20(Official%20Music%20Video).mp3", // Ed Sheeran - Perfect (Official Music Video).mp3
  "85": "/music/Ed%20Sheeran%20-%20Thinking%20Out%20Loud%20(Official%20Music%20Video).mp3", // Ed Sheeran - Thinking Out Loud (Official Music Video).mp3
  "86": "/music/Elvis%20Presley%20-%20Can't%20Help%20Falling%20In%20Love%20(Official%20Audio).mp3", // Elvis Presley - Can't Help Falling In Love (Official Audio).mp3
  "87": "/music/Taylor%20Swift%20-%20Lover%20(Official%20Music%20Video).mp3", // Taylor Swift - Lover (Official Music Video).mp3
  "88": "/music/Taylor%20Swift%20-%20Wildest%20Dreams.mp3", // Taylor Swift - Wildest Dreams.mp3
  "240": "/music/Passenger%20%EF%BD%9C%20Let%20Her%20Go%20(Official%20Video).mp3", // Passenger ｜ Let Her Go (Official Video).mp3
  "241": "/music/Dean%20Lewis%20-%20With%20You%20(Official%20Video).mp3", // Dean Lewis - With You (Official Video).mp3
  "242": "/music/Dean%20Lewis%20-%20Waves%20(Official%20Video).mp3", // Dean Lewis - Waves (Official Video).mp3
  "243": "/music/Sam%20Smith%20-%20Stay%20With%20Me%20(Official%20Music%20Video).mp3", // Sam Smith - Stay With Me (Official Music Video).mp3
  "244": "/music/Faouzia%20%26%20John%20Legend%20-%20Minefields%20(Official%20Music%20Video).mp3", // Faouzia & John Legend - Minefields (Official Music Video).mp3
  "245": "/music/Mark%20Ambor%20-%20Belong%20Together%20(Official%20Lyric%20Video).mp3", // Mark Ambor - Belong Together (Official Lyric Video).mp3
  "246": "/music/OneRepublic%20-%20Let's%20Hurt%20Tonight.mp3", // OneRepublic - Let's Hurt Tonight.mp3
  "247": "/music/Elton%20John%2C%20Dua%20Lipa%20-%20Cold%20Heart%20(PNAU%20Remix)%20(Official%20Video).mp3", // Elton John, Dua Lipa - Cold Heart (PNAU Remix) (Official Video).mp3
  "408": "/music/Yazoo%20-%20Only%20You%20%E2%80%A2%20TopPop.mp3", // Yazoo - Only You • TopPop.mp3
  "409": "/music/Charlotte%20OC%20-%20Colour%20My%20Heart%20(Official%20Video).mp3", // Charlotte OC - Colour My Heart (Official Video).mp3
  "410": "/music/Bobby%20Bazini%20-%20Blood's%20Thicker%20Than%20Water%20(Audio).mp3", // Bobby Bazini - Blood's Thicker Than Water (Audio).mp3
  "411": "/music/Mirror%20Fury%20-%20The%20One%20I%20Love.mp3", // Mirror Fury - The One I Love.mp3
  "100": "/music/Queen%20%E2%80%93%20Bohemian%20Rhapsody%20(Official%20Video%20Remastered).mp3", // Queen – Bohemian Rhapsody (Official Video Remastered).mp3
  "101": "/music/Hotel%20California%20(2013%20Remaster).mp3", // Hotel California (2013 Remaster).mp3
  "102": "/music/Led%20Zeppelin%20-%20Stairway%20To%20Heaven%20(Official%20Audio).mp3", // Led Zeppelin - Stairway To Heaven (Official Audio).mp3
  "103": "/music/Pink%20Floyd%20-%20Comfortably%20numb.mp3", // Pink Floyd - Comfortably numb.mp3
  "104": "/music/Pink%20Floyd%20-%20Wish%20You%20Were%20Here.mp3", // Pink Floyd - Wish You Were Here.mp3
  "105": "/music/Let%20It%20Be%20(Remastered%202009).mp3", // Let It Be (Remastered 2009).mp3
  "106": "/music/The%20Beatles%20-%20The%20Beatles%20-%20Hey%20Jude%20(Official%20Music%20Video)%20%5BRemastered%202015%5D.mp3", // The Beatles - The Beatles - Hey Jude (Official Music Video) [Remastered 2015].mp3
  "107": "/music/Imagine%20-%20John%20Lennon%20%26%20The%20Plastic%20Ono%20Band%20(w%20The%20Flux%20Fiddlers)%20(Ultimate%20Mix%202018)%20-%204K%20REMASTER.mp3", // Imagine - John Lennon & The Plastic Ono Band (w The Flux Fiddlers) (Ultimate Mix 2018) - 4K REMASTER.mp3
  "108": "/music/David%20Bowie%20-%20Space%20Oddity%20(Official%20Video).mp3", // David Bowie - Space Oddity (Official Video).mp3
  "109": "/music/David%20Bowie%20-%20%EF%BC%82Heroes%EF%BC%82%20(Official%20Video)%20%5BHD%5D.mp3", // David Bowie - ＂Heroes＂ (Official Video) [HD].mp3
  "110": "/music/The%20Police%20-%20Roxanne%20(Official%20Music%20Video).mp3", // The Police - Roxanne (Official Music Video).mp3
  "111": "/music/The%20Police%20-%20Every%20Breath%20You%20Take%20(Official%20Music%20Video).mp3", // The Police - Every Breath You Take (Official Music Video).mp3
  "112": "/music/Toto%20-%20Africa%20(Official%20HD%20Video).mp3", // Toto - Africa (Official HD Video).mp3
  "113": "/music/a-ha%20-%20Take%20On%20Me%20(Official%20Video)%20%5B4K%5D.mp3", // a-ha - Take On Me (Official Video) [4K].mp3
  "114": "/music/Simple%20Minds%20-%20Don't%20You%20(Forget%20About%20Me).mp3", // Simple Minds - Don't You (Forget About Me).mp3
  "250": "/music/Alphaville%20-%20Big%20In%20Japan%20(Official%20Music%20Video).mp3", // Alphaville - Big In Japan (Official Music Video).mp3
  "251": "/music/Tears%20For%20Fears%20-%20Everybody%20Wants%20To%20Rule%20The%20World%20(Official%20Music%20Video).mp3", // Tears For Fears - Everybody Wants To Rule The World (Official Music Video).mp3
  "252": "/music/The%20Cranberries%20-%20Zombie%20(Official%20Music%20Video).mp3", // The Cranberries - Zombie (Official Music Video).mp3
  "253": "/music/Louis%20Armstrong%20-%20What%20A%20Wonderful%20World%20(Official%20Video).mp3", // Louis Armstrong - What A Wonderful World (Official Video).mp3
  "254": "/music/Man%20in%20the%20Mirror%20-%20Michael%20Jackson.mp3", // Man in the Mirror — file may not exist, will fall back gracefully
  "255": "/music/Neil%20Diamond%20-%20Sweet%20Caroline%20(Audio).mp3", // Neil Diamond - Sweet Caroline (Audio).mp3
  "256": "/music/Scorpions%20-%20Wind%20Of%20Change%20(Official%20Music%20Video).mp3", // Scorpions - Wind Of Change (Official Music Video).mp3
  "257": "/music/The%20Proclaimers%20-%20I'm%20Gonna%20Be%20(500%20Miles)%20(Official%20Music%20Video).mp3", // The Proclaimers - I'm Gonna Be (500 Miles) (Official Music Video).mp3
  "258": "/music/George%20Michael%2C%20Elton%20John%20-%20Don't%20Let%20The%20Sun%20Go%20Down%20On%20Me%20(Live).mp3", // George Michael, Elton John - Don't Let The Sun Go Down On Me (Live).mp3
  "259": "/music/I%20Don't%20Want%20to%20Miss%20a%20Thing%20-%20Aerosmith.mp3", // I Don't Want to Miss a Thing — file may not exist, will fall back
  "260": "/music/Lean%20on%20Me.mp3", // Lean on Me.mp3
  "261": "/music/Bill%20Withers%20-%20Ain't%20No%20Sunshine%20(Official%20Audio).mp3", // Bill Withers - Ain't No Sunshine (Official Audio).mp3
  "262": "/music/Ben%20E.%20King%20-%20Stand%20By%20Me%20(Audio).mp3", // Ben E. King - Stand By Me (Audio).mp3
  "263": "/music/Elton%20John%20-%20I'm%20Still%20Standing.mp3", // Elton John - I'm Still Standing.mp3
  "264": "/music/Eagle-Eye%20Cherry%20-%20Save%20Tonight.mp3", // Eagle-Eye Cherry - Save Tonight.mp3
  "265": "/music/Bon%20Jovi%20-%20It's%20My%20Life%20(Official%20Music%20Video).mp3", // Bon Jovi - It's My Life (Official Music Video).mp3
  "266": "/music/X%20Ambassadors%20-%20Renegades%20(Lyric%20Video).mp3", // X Ambassadors - Renegades (Lyric Video).mp3
  "267": "/music/Bill%20Withers%20-%20Lovely%20Day%20(Official%20Audio).mp3", // Bill Withers - Lovely Day (Official Audio).mp3
  "268": "/music/The%20Veils%20-%20Grey%20Lynn%20Park.mp3", // The Veils - Grey Lynn Park.mp3
  "269": "/music/Dobie%20Gray%20-%20Drift%20Away%20(Original%20Official%20Video).mp3", // Dobie Gray - Drift Away (Original Official Video).mp3
  "270": "/music/The%20Verve%20-%20Bitter%20Sweet%20Symphony.mp3", // The Verve - Bitter Sweet Symphony.mp3
  "271": "/music/4%20Non%20Blondes%20-%20What's%20Up%20(Official%20Music%20Video).mp3", // 4 Non Blondes - What's Up (Official Music Video).mp3
  "272": "/music/Deep%20Blue%20Something%20-%20Breakfast%20At%20Tiffany's%20(Official%20Music%20Video).mp3", // Deep Blue Something - Breakfast At Tiffany's (Official Music Video).mp3
  "273": "/music/Tina%20Turner%20-%20The%20Best%20(Official%20Music%20Video)%20%5BHD%20Upgrade%5D.mp3", // Tina Turner - The Best (Official Music Video) [HD Upgrade].mp3
  "412": "/music/TINA%20TURNER%20%E2%98%85%20We%20Don't%20Need%20Another%20Hero%20(Thunderdome)%E3%80%90music%20video%E3%80%91.mp3", // TINA TURNER ★ We Don't Need Another Hero (Thunderdome)【music video】.mp3
  "413": "/music/Johnny%20Clegg-Great%20Heart.mp3", // Johnny Clegg-Great Heart.mp3
  "414": "/music/Johnny%20Clegg%20-%20King%20Of%20Time.mp3", // Johnny Clegg - King Of Time.mp3
  "416": "/music/Hold%20On%2C%20I'm%20Coming.mp3", // Hold On, I'm Coming.mp3
  "417": "/music/Stuck%20On%20You.mp3", // Stuck On You.mp3
  "418": "/music/THE%20CROSSING%20-%20Friends%20of%20Johnny%20Clegg.mp3", // THE CROSSING - Friends of Johnny Clegg.mp3
  "419": "/music/Luude%20-%20Down%20Under%20(Feat.%20Colin%20Hay)%20(Official%20Music%20Video).mp3", // Luude - Down Under (Feat. Colin Hay) (Official Music Video).mp3
  "130": "/music/M83%20'Midnight%20City'%20Official%20video.mp3", // M83 'Midnight City' Official video.mp3
  "132": "/music/Erykah%20Badu%20-%20On%20%26%20On%20(Remix%20Edit).mp3", // Erykah Badu - On & On (Remix Edit).mp3
  "133": "/music/Childish%20Gambino%20-%20Redbone%20(Lyrics).mp3", // Childish Gambino - Redbone (Lyrics).mp3
  "134": "/music/Arctic%20Monkeys%20-%20Do%20I%20Wanna%20Know%EF%BC%9F%20(Official%20Video).mp3", // Arctic Monkeys - Do I Wanna Know？ (Official Video).mp3
  "135": "/music/Arctic%20Monkeys%20-%20R%20U%20Mine%EF%BC%9F%20(Official%20Video).mp3", // Arctic Monkeys - R U Mine？ (Official Video).mp3
  "136": "/music/Arctic%20Monkeys%20-%20505.mp3", // Arctic Monkeys - 505.mp3
  "138": "/music/MGMT%20-%20Electric%20Feel%20(Official%20HD%20Video).mp3", // MGMT - Electric Feel (Official HD Video).mp3
  "139": "/music/MGMT%20-%20Kids%20(Lyrics).mp3", // MGMT - Kids (Lyrics).mp3
  "280": "/music/Sheppard%20-%20Geronimo%20(Official%20Music%20Video).mp3", // Sheppard - Geronimo (Official Music Video).mp3
  "281": "/music/George%20Ezra%20-%20Budapest%20(Official%20Video).mp3", // George Ezra - Budapest (Official Video).mp3
  "282": "/music/Martin%20Garrix%20feat.%20Bonn%20-%20High%20On%20Life%20(Official%20Video).mp3", // Martin Garrix feat. Bonn - High On Life (Official Video).mp3
  "283": "/music/Ini%20Kamoze%20-%20Here%20Comes%20The%20Hotstepper%20(Remix)%20(Official%20Video).mp3", // Ini Kamoze - Here Comes The Hotstepper (Remix) (Official Video).mp3
  "284": "/music/John%20Newman%20-%20Love%20Me%20Again.mp3", // John Newman - Love Me Again.mp3
  "285": "/music/The%20Weeknd%20-%20Can't%20Feel%20My%20Face%20(Official%20Video).mp3", // The Weeknd - Can't Feel My Face (Official Video).mp3
  "420": "/music/Talk%20Is%20Cheap.mp3", // Talk Is Cheap.mp3
  "421": "/music/Feel%20-%20Avi%20Snow%2C%20MVCA%2C%20Zeeba%20(AI%20Music%20Video).mp3", // Feel - Avi Snow, MVCA, Zeeba (AI Music Video).mp3
  "422": "/music/Dezko%20%26%20CERES%20-%20U%26ME%20(Visualizer).mp3", // Dezko & CERES - U&ME (Visualizer).mp3
  "423": "/music/In%20The%20Air%20Tonight-%20%20Jon%20Howard%20(Official%20Audio).mp3", // In The Air Tonight-  Jon Howard (Official Audio).mp3
  "424": "/music/Livin%E2%80%99%20on%20Borrowed%20Time.mp3", // Livin’ on Borrowed Time.mp3
  "425": "/music/Croixx%20-%20Higher%20(Official%20Lyric%20Video).mp3", // Croixx - Higher (Official Lyric Video).mp3
  "426": "/music/Martin%20Wave%20feat.%20ASHBY%20-%20Watch%20Me%20Die%20(From%20The%20Terminal%20List)%20%5BFULL%20SONG%5D.mp3", // Martin Wave feat. ASHBY - Watch Me Die (From The Terminal List) [FULL SONG].mp3
  "427": "/music/Here%20We%20Go.mp3", // Here We Go.mp3
  "428": "/music/Hanni%20El%20Khatib%20-%20Nobody%20Move.mp3", // Hanni El Khatib - Nobody Move.mp3
  "429": "/music/Manike%20(Full%20Video)%EF%BC%9A%20Thank%20God%20%EF%BD%9C%20Nora%2CSidharth%EF%BD%9C%20Tanishk%2CYohani%2CJubin%2CSurya%20R%20%EF%BD%9CRashmi%20Virag%EF%BD%9CBhushan%20K.mp3", // Manike (Full Video)： Thank God ｜ Nora,Sidharth｜ Tanishk,Yohani,Jubin,Surya R ｜Rashmi Virag｜Bhushan K.mp3
  "430": "/music/Cadbury%20Gorilla%20-%20In%20The%20Air%20Tonight%20(Extended%20Mix).mp3", // Cadbury Gorilla - In The Air Tonight (Extended Mix).mp3
  "150": "/music/The%20Weeknd%20-%20Blinding%20Lights%20(Official%20Video).mp3", // The Weeknd - Blinding Lights (Official Video).mp3
  "151": "/music/The%20Weeknd%20-%20Starboy%20ft.%20Daft%20Punk%20(Official%20Video)%20ft.%20Daft%20Punk.mp3", // The Weeknd - Starboy ft. Daft Punk (Official Video) ft. Daft Punk.mp3
  "152": "/music/Post%20Malone%20-%20Circles.mp3", // Post Malone - Circles.mp3
  "153": "/music/Post%20Malone%2C%20Swae%20Lee%20-%20Sunflower%20(Spider-Man%EF%BC%9A%20Into%20the%20Spider-Verse).mp3", // Post Malone, Swae Lee - Sunflower (Spider-Man： Into the Spider-Verse).mp3
  "154": "/music/Dua%20Lipa%20-%20Levitating%20Featuring%20DaBaby%20(Official%20Music%20Video).mp3", // Dua Lipa - Levitating Featuring DaBaby (Official Music Video).mp3
  "155": "/music/Harry%20Styles%20-%20As%20It%20Was%20(Official%20Video).mp3", // Harry Styles - As It Was (Official Video).mp3
  "156": "/music/Glass%20Animals%20-%20Heat%20Waves%20(Official%20Video).mp3", // Glass Animals - Heat Waves (Official Video).mp3
  "157": "/music/JVKE%20-%20golden%20hour%20(official%20music%20video).mp3", // JVKE - golden hour (official music video).mp3
  "158": "/music/Taylor%20Swift%20-%20Anti-Hero%20(Official%20Music%20Video).mp3", // Taylor Swift - Anti-Hero (Official Music Video).mp3
  "159": "/music/Miley%20Cyrus%20-%20Flowers%20(Official%20Video).mp3", // Miley Cyrus - Flowers (Official Video).mp3
  "160": "/music/Taylor%20Swift%20-%20Cruel%20Summer%20(Official%20Audio).mp3", // Taylor Swift - Cruel Summer (Official Audio).mp3
  "161": "/music/Justin%20Bieber%20-%20Peaches%20ft.%20Daniel%20Caesar%2C%20Giveon.mp3", // Justin Bieber - Peaches ft. Daniel Caesar, Giveon.mp3
  "290": "/music/Rag'n'Bone%20Man%20-%20Skin%20(Official%20Video).mp3", // Rag'n'Bone Man - Skin (Official Video).mp3
  "291": "/music/Scrubs%20Theme%20Song%20%E2%80%9CSuperman%E2%80%9D%20Lazlo%20Bane%20Official%20Video%20Remastered%20HD.mp3", // Scrubs Theme Song “Superman” Lazlo Bane Official Video Remastered HD.mp3
  "431": "/music/Machine%20Gun%20Kelly%2C%20X%20Ambassadors%20%26%20Bebe%20Rexha%20-%20Home%20(from%20Bright%EF%BC%9A%20The%20Album)%20%5BOfficial%20Video%5D.mp3", // Machine Gun Kelly, X Ambassadors & Bebe Rexha - Home (from Bright： The Album) [Official Video].mp3
  "432": "/music/Alex%20Warren%20-%20Ordinary%20(Official%20Video).mp3", // Alex Warren - Ordinary (Official Video).mp3
  "433": "/music/all%20things%20break%20-%20magnetic%20magnetic.mp3", // all things break - magnetic magnetic.mp3
  "434": "/music/Never%20Did.mp3", // Never Did.mp3
  "435": "/music/ROYA%20-%20Cruise%20(Extended%20Version)%20-%20LIVE%20SESSION.mp3", // ROYA - Cruise (Extended Version) - LIVE SESSION.mp3
  "436": "/music/Astrality%20%26%20James%20French%20-%20Can%E2%80%99t%20Go%20Back.mp3", // Astrality & James French - Can’t Go Back.mp3
  "437": "/music/Hold%20On%20Hope.mp3", // Hold On Hope.mp3
  "438": "/music/OneRepublic%20-%20Need%20Your%20Love%20(Official%20Video).mp3", // OneRepublic - Need Your Love (Official Video).mp3
  "439": "/music/Madonna%20-%20Like%20A%20Prayer%20(Choir%20Version)%20%5BVinyl%20Visualizer%5D.mp3", // Madonna - Like A Prayer (Choir Version) [Vinyl Visualizer].mp3
  "440": "/music/O%20Meri%20Laila%20-%20Lyrical%20%EF%BD%9C%20Laila%20Majnu%20%EF%BD%9C%20Jyotica%20Tangri%20%EF%BD%9C%20Avinash%20Tiwary%20%26%20Tripti%20Dimri.mp3", // O Meri Laila - Lyrical ｜ Laila Majnu ｜ Jyotica Tangri ｜ Avinash Tiwary & Tripti Dimri.mp3
  "441": "/music/Logic%20%26%20Rag'n'Bone%20Man%20-%20Broken%20People%20(from%20Bright%EF%BC%9A%20The%20Album)%20%5BOfficial%20Lyric%20Video%5D.mp3", // Logic & Rag'n'Bone Man - Broken People (from Bright： The Album) [Official Lyric Video].mp3
  "310": "/music/One%20Last%20Waltz%20%E2%80%93%20DannyHO%20%EF%BD%9C%20Minecraft-Style%20EDM%20Visual%20%EF%BD%9C%20Afterglow%20(Track%2007).mp3", // One Last Waltz – DannyHO ｜ Minecraft-Style EDM Visual ｜ Afterglow (Track 07).mp3
  "311": "/music/Against%20the%20Tide%20%E2%80%93%20DannyHO%20%EF%BD%9C%20Minecraft-Style%20EDM%20Visual%20%EF%BD%9C%20Afterglow%20(Track%2004).mp3", // Against the Tide – DannyHO ｜ Minecraft-Style EDM Visual ｜ Afterglow (Track 04).mp3
  "312": "/music/Tell%20Me%20Why%20-%20Supermode.mp3", // Tell Me Why — not yet downloaded, audio will silently skip
  "313": "/music/Elderbrook%20-%20Inner%20Light%20with%20Bob%20Moses%20(Official%20Music%20Video).mp3", // Elderbrook - Inner Light with Bob Moses (Official Music Video).mp3
  "314": "/music/Imagine%20Dragons%20-%20Shots%20(Broiler%20Remix)%20ft.%20Broiler.mp3", // Imagine Dragons - Shots (Broiler Remix) ft. Broiler.mp3
  "442": "/music/Stealth%20-%20Judgement%20Day.mp3", // Stealth - Judgement Day.mp3
  "443": "/music/Zac%20Brown%20%26%20Sir%20Rosevelt%20-%20It%20Goes%20On%20(Official%20Lyric%20Video).mp3", // Zac Brown & Sir Rosevelt - It Goes On (Official Lyric Video).mp3
  "444": "/music/Break%20The%20Silence%20%E2%A7%B8%E2%A7%B8%20The%20Dig%20%E2%A7%B8%E2%A7%B8%20Midnight%20Flowers%20(2012).mp3", // Break The Silence ⧸⧸ The Dig ⧸⧸ Midnight Flowers (2012).mp3
  "445": "/music/Desi%20Valentine%20-%20Fate%20Don't%20Know%20You.mp3", // Desi Valentine - Fate Don't Know You.mp3
  "131": "/music/Intro.mp3", // Intro.mp3 (The xx)
  "300": "/music/The%20Three%20Tenors%20in%20Concert%201994%EF%BC%9A%20%EF%BC%82Nessun%20Dorma%EF%BC%82%20from%20Turandot%20(encore).mp3", // The Three Tenors in Concert 1994： ＂Nessun Dorma＂ from Turandot (encore).mp3
  "301": "/music/A.R.%20Rahman%20-%20Tere%20Bina%20%EF%BD%9C%20Lyrical%20Song%20%EF%BD%9C%20Aishwarya%20Rai%20%EF%BD%9C%20Abhishek%20Bachchan%20%EF%BD%9C%20Guru%20%EF%BD%9C%20Gulzar.mp3", // A.R. Rahman - Tere Bina ｜ Lyrical Song ｜ Aishwarya Rai ｜ Abhishek Bachchan ｜ Guru ｜ Gulzar.mp3
  "446": "/music/Robbie%20Williams%20-%20Man%20For%20All%20Seasons%20(Johnny%20English).mp3", // Robbie Williams - Man For All Seasons (Johnny English).mp3
  "447": "/music/The%20Angry%20River%20-%20The%20Hat%20ft.%20father%20John%20Misty%20(with%20lyrics).mp3", // The Angry River - The Hat ft. father John Misty (with lyrics).mp3
  "448": "/music/Lera%20Lynn%20-%20Lately.mp3", // Lera Lynn - Lately.mp3
  "449": "/music/Psych%20Theme%20Song%20(Full%20Version)~Friendly%20Indians.mp3", // Psych Theme Song (Full Version)~Friendly Indians.mp3
  "450": "/music/Turin%20Brakes%20-%20Save%20You%20(Official%20Video).mp3", // Turin Brakes - Save You (Official Video).mp3
};
