import { NextResponse } from "next/server";

// Static list — no fs import, keeps the serverless function tiny.
// Re-run `node scripts/gen-music-list.js` (or update manually) when tracks change.
const FILES: string[] = [
  "＂Suite＂ - Pirates of the Caribbean (Klaus Badelt) - Film Symphony Orchestra.mp3",
  "4 Non Blondes - What's Up (Official Music Video).mp3",
  "a-ha - Take On Me (Official Video) [4K].mp3",
  "A.R. Rahman - Tere Bina ｜ Lyrical Song ｜ Aishwarya Rai ｜ Abhishek Bachchan ｜ Guru ｜ Gulzar.mp3",
  "Adele - Make You Feel My Love (Official Video).mp3",
  "Adele - Someone Like You (Official Music Video).mp3",
  "Against the Tide – DannyHO ｜ Minecraft-Style EDM Visual ｜ Afterglow (Track 04).mp3",
  "Alex Warren - Ordinary (Official Video).mp3",
  "Alphaville - Big In Japan (Official Music Video).mp3",
  "Anna Nalick - Breathe (2 AM) (Official Video).mp3",
  "Arctic Monkeys - 505.mp3",
  "Arctic Monkeys - Do I Wanna Know？ (Official Video).mp3",
  "Arctic Monkeys - R U Mine？ (Official Video).mp3",
  "Ben E. King - Stand By Me (Audio).mp3",
  "Bill Withers - Ain't No Sunshine (Official Audio).mp3",
  "Bill Withers - Lovely Day (Official Audio).mp3",
  "Bon Iver - Holocene - Official Video.mp3",
  "Bon Jovi - It's My Life (Official Music Video).mp3",
  "Bon Jovi - Young Guns II Blaze of Glory.mp3",
  "Casino Royale - Chris Cornell - You Know My Name.mp3",
  "Céline Dion - My Heart Will Go On (Official 25th Anniversary Alternate Music Video).mp3",
  "Childish Gambino - Redbone (Lyrics).mp3",
  "Christina Perri - A Thousand Years [Official Music Video].mp3",
  "CLAUDE DEBUSSY：  CLAIR DE LUNE.mp3",
  "Coldplay - A Sky Full Of Stars (Official Video).mp3",
  "Coldplay - Charlie Brown (Official Video).mp3",
  "Coldplay - Clocks (Official Video).mp3",
  "Coldplay - Everglow [Single Version] - (Official Video).mp3",
  "Coldplay - Every Teardrop Is a Waterfall (Official Video).mp3",
  "Coldplay - Fix You (Official Video).mp3",
  "Coldplay - In My Place (Official 4K Video).mp3",
  "Coldplay - Magic (Official Video).mp3",
  "Coldplay - Miracles (Official Lyric Video).mp3",
  "Coldplay - Paradise (Official Video).mp3",
  "Coldplay - Shiver (Official Video).mp3",
  "Coldplay - Speed Of Sound (Official Video).mp3",
  "Coldplay - The Hardest Part (Official Video).mp3",
  "Coldplay - The Scientist (Official 4K Video).mp3",
  "Coldplay - Trouble (Official video).mp3",
  "Coldplay - Up&Up (Official Video).mp3",
  "Coldplay - Violet Hill (Official Video).mp3",
  "Coldplay - Viva La Vida (Official Video).mp3",
  "Coldplay - Yellow (Official Video).mp3",
  "Comptine d'un autre été, l'après-midi.mp3",
  "Daughter - Youth.mp3",
  "David Bowie - ＂Heroes＂ (Official Video) [HD].mp3",
  "David Bowie - Space Oddity (Official Video).mp3",
  "Dean Lewis - Waves (Official Video).mp3",
  "Dean Lewis - With You (Official Video).mp3",
  "Deep Blue Something - Breakfast At Tiffany's (Official Music Video).mp3",
  "Dobie Gray - Drift Away (Original Official Video).mp3",
  "Dua Lipa - Levitating Featuring DaBaby (Official Music Video).mp3",
  "Eagle-Eye Cherry - Save Tonight.mp3",
  "Ed Sheeran - Perfect (Official Music Video).mp3",
  "Ed Sheeran - Thinking Out Loud (Official Music Video).mp3",
  "Elderbrook - Inner Light with Bob Moses (Official Music Video).mp3",
  "Elton John - I'm Still Standing.mp3",
  "Elton John, Dua Lipa - Cold Heart (PNAU Remix) (Official Video).mp3",
  "Elvis Presley - Can't Help Falling In Love (Official Audio).mp3",
  "Erik Satie - Gymnopédie No.1.mp3",
  "Erykah Badu - On & On (Remix Edit).mp3",
  "Faouzia & John Legend - Minefields (Official Music Video).mp3",
  "George Ezra - Budapest (Official Video).mp3",
  "George Michael, Elton John - Don't Let The Sun Go Down On Me (Live).mp3",
  "Gladiator • Now We Are Free • Hans Zimmer & Lisa Gerrard.mp3",
  "Glass Animals - Heat Waves (Official Video).mp3",
  "Godzilla Soundtrack ｜ Godzilla! - Alexandre Desplat ｜ WaterTower Music.mp3",
  "Hans Zimmer - A Dark Knight ｜ EPIC VERSION.mp3",
  "Hans Zimmer - Time (Inception).mp3",
  "Harry Styles - As It Was (Official Video).mp3",
  "Hotel California (2013 Remaster).mp3",
  "Ima Robot - Greenback Boogie - (official video).mp3",
  "Imagine - John Lennon & The Plastic Ono Band (w The Flux Fiddlers) (Ultimate Mix 2018) - 4K REMASTER.mp3",
  "Imagine Dragons - Shots (Broiler Remix) ft. Broiler.mp3",
  "Ini Kamoze - Here Comes The Hotstepper (Remix) (Official Video).mp3",
  "Interstellar Main Theme - Hans Zimmer.mp3",
  "Intro.mp3",
  "Jacob Banks - Unknown (To You) Official Music Video.mp3",
  "James Bay - Hold Back The River.mp3",
  "Jamie N Commons - Lead Me Home (The Walking Dead).mp3",
  "John Legend - All of Me (Official Video).mp3",
  "John Newman - Love Me Again.mp3",
  "Johnny Clegg-Great Heart.mp3",
  "José González - Stay Alive.mp3",
  "Justin Bieber - Peaches ft. Daniel Caesar, Giveon.mp3",
  "JVKE - golden hour (official music video).mp3",
  "Kacey Musgraves - Slow Burn (Official Audio).mp3",
  "KALEO - Way Down We Go (Official Music Video).mp3",
  "Keane - Somewhere Only We Know (Official Music Video).mp3",
  "Lean on Me.mp3",
  "Led Zeppelin - Stairway To Heaven (Official Audio).mp3",
  "Let It Be (Remastered 2009).mp3",
  "Lewis Capaldi - Before You Go (Official Video).mp3",
  "Louis Armstrong - What A Wonderful World (Official Video).mp3",
  "Ludovico Einaudi - Divenire (Live from The Royal Albert Hall London ⧸ 2010).mp3",
  "Ludovico Einaudi - Experience (Live from Teatro dal Verme, Milano).mp3",
  "Ludovico Einaudi - Nuvole Bianche (Live From The Steve Jobs Theatre ⧸ 2019).mp3",
  "M83 'Midnight City' Official video.mp3",
  "Mark Ambor - Belong Together (Official Lyric Video).mp3",
  "Martin Garrix feat. Bonn - High On Life (Official Video).mp3",
  "Medicine.mp3",
  "MGMT - Electric Feel (Official HD Video).mp3",
  "MGMT - Kids (Lyrics).mp3",
  "Michael Kiwanuka - Love & Hate (Live Session).mp3",
  "Miley Cyrus - Flowers (Official Video).mp3",
  "Neil Diamond - Sweet Caroline (Audio).mp3",
  "One Last Waltz – DannyHO ｜ Minecraft-Style EDM Visual ｜ Afterglow (Track 07).mp3",
  "OneRepublic - Let's Hurt Tonight.mp3",
  "Passenger ｜ Let Her Go (Official Video).mp3",
  "Pink Floyd - Comfortably numb.mp3",
  "Pink Floyd - Wish You Were Here.mp3",
  "Pirates Of The Caribbean Theme Song.mp3",
  "Post Malone - Circles.mp3",
  "Post Malone, Swae Lee - Sunflower (Spider-Man： Into the Spider-Verse).mp3",
  "Queen – Bohemian Rhapsody (Official Video Remastered).mp3",
  "Rag'n'Bone Man - Human (Official Video).mp3",
  "Rag'n'Bone Man - Skin (Official Video).mp3",
  "Requiem For A Dream Full Song HD.mp3",
  "Rocky Balboa - Theme Song (HD).mp3",
  "Ruth B. - Dandelions (Lyrics).mp3",
  "Sam Smith - Stay With Me (Official Music Video).mp3",
  "Scorpions - Wind Of Change (Official Music Video).mp3",
  "Scrubs Theme Song \"Superman\" Lazlo Bane Official Video Remastered HD.mp3",
  "Sheppard - Geronimo (Official Music Video).mp3",
  "Simple Minds - Don't You (Forget About Me).mp3",
  "Skinny Love.mp3",
  "Snow Patrol - Open Your Eyes (Official Video).mp3",
  "Star Wars： Duel of The Fates ｜ EPIC VERSION (Remastered V2).mp3",
  "Stateless - Bloodstream (Official lyrics).mp3",
  "Succession (Main Title Theme) - Nicholas Britell ｜ Succession (HBO Original Series Soundtrack).mp3",
  "Survivor - Burning heart (Rocky IV) HQ.mp3",
  "Survivor - Eye Of The Tiger (Official HD Video).mp3",
  "Talk Is Cheap.mp3",
  "Taylor Swift - Anti-Hero (Official Music Video).mp3",
  "Taylor Swift - Cruel Summer (Official Audio).mp3",
  "Taylor Swift - Lover (Official Music Video).mp3",
  "Taylor Swift - Wildest Dreams.mp3",
  "Tears For Fears - Everybody Wants To Rule The World (Official Music Video).mp3",
  "The Beatles - The Beatles - Hey Jude (Official Music Video) [Remastered 2015].mp3",
  "The Cranberries - Zombie (Official Music Video).mp3",
  "The Dark Knight Rises Official Soundtrack ｜ Why Do We Fall？ – Hans Zimmer ｜ WaterTower.mp3",
  "The Godfather Waltz.mp3",
  "The Police - Every Breath You Take (Official Music Video).mp3",
  "The Police - Roxanne (Official Music Video).mp3",
  "The Proclaimers - I'm Gonna Be (500 Miles) (Official Music Video).mp3",
  "The Three Tenors in Concert 1994： ＂Nessun Dorma＂ from Turandot (encore).mp3",
  "The Veils - Grey Lynn Park.mp3",
  "The Verve - Bitter Sweet Symphony.mp3",
  "The Weeknd - Blinding Lights (Official Video).mp3",
  "The Weeknd - Can't Feel My Face (Official Video).mp3",
  "The Weeknd - Starboy ft. Daft Punk (Official Video) ft. Daft Punk.mp3",
  "The XX Intro - ELEZO remix ( Official video ).mp3",
  "Tina Turner - The Best (Official Music Video) [HD Upgrade].mp3",
  "Toto - Africa (Official HD Video).mp3",
  "Treadstone Assassins.mp3",
  "X Ambassadors - Renegades (Lyric Video).mp3",
  "Yiruma, (이루마) - River Flows in You.mp3",
];

export const dynamic = "force-static";

export async function GET() {
  return NextResponse.json({ files: FILES });
}
