#!/usr/bin/env node
/**
 * Generates src/lib/track-src-map.ts from actual files in public/music/
 * Run: node scripts/gen-src-map.js
 */
const fs   = require("fs");
const path = require("path");

const musicDir  = path.join(__dirname, "..", "public", "music");
const dataFile  = path.join(__dirname, "..", "src", "lib", "data.ts");
const outFile   = path.join(__dirname, "..", "src", "lib", "track-src-map.ts");

// ── Read all mp3 filenames ────────────────────────────────
const files = fs.readdirSync(musicDir).filter(f => f.endsWith(".mp3"));

// ── Parse tracks from data.ts ─────────────────────────────
const src  = fs.readFileSync(dataFile, "utf8");
const rows = [];

// Match each track object: id, title, artist
const lineRe = /id:\s*"(\d+)"[^}]+?title:\s*"([^"]+)"[^}]+?artist:\s*"([^"]+)"/g;
let m;
while ((m = lineRe.exec(src)) !== null) {
  rows.push({ id: m[1], title: m[2], artist: m[3] });
}

// ── Fuzzy scorer ──────────────────────────────────────────
function norm(s) {
  return s.toLowerCase()
    .replace(/[&＂'"''""\u{FF02}\u{2019}\u{2018}]/gu, "")
    .replace(/[^a-z0-9]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function bestMatch(title, artist) {
  const words = [...norm(title).split(" "), ...norm(artist).split(" ")]
    .filter(w => w.length > 2);
  let best = null, hi = 0;
  for (const f of files) {
    const fn = norm(f.replace(/\.mp3$/i, ""));
    const s  = words.filter(w => fn.includes(w)).length;
    if (s > hi) { hi = s; best = f; }
  }
  return { file: best, score: hi };
}

// ── Build map ─────────────────────────────────────────────
const entries = [];
const issues  = [];

for (const row of rows) {
  const { file, score } = bestMatch(row.title, row.artist);
  if (!file || score < 1) {
    issues.push(`  // MISSING (score=${score}): ${row.id} — ${row.artist} - ${row.title}`);
    entries.push(`  // "id":"${row.id}" — NO FILE FOUND for: ${row.artist} - ${row.title}`);
  } else {
    const enc = "/music/" + encodeURIComponent(file);
    entries.push(`  "${row.id}": "${enc}", // ${file}`);
    if (score < 2) {
      issues.push(`  // LOW CONFIDENCE (score=${score}): ${row.id} "${row.title}" by ${row.artist} => ${file}`);
    }
  }
}

// ── Write output ──────────────────────────────────────────
const ts = `/**
 * AUTO-GENERATED by scripts/gen-src-map.js — do not edit by hand.
 * Run "node scripts/gen-src-map.js" to regenerate after adding music files.
 *
 * Maps track ID -> exact URL-encoded /music/ path, resolved from real filenames.
 * Player uses this for instant zero-latency audio resolution.
 */
export const TRACK_SRC_MAP: Record<string, string> = {
${entries.join("\n")}
};
`;

fs.writeFileSync(outFile, ts, "utf8");

console.log(`\nGenerated ${outFile}`);
console.log(`  ${rows.length} tracks processed`);
console.log(`  ${issues.filter(l => l.includes("MISSING")).length} missing files`);
console.log(`  ${issues.filter(l => l.includes("LOW")).length} low-confidence matches`);

if (issues.length) {
  console.log("\nIssues to review:");
  issues.forEach(l => console.log(l));
}
